### PR TITLE
Dekalb: Ready for review

### PR DESCRIPTION
**Pull request by rimjieun**
Pretty much done. Instructions on README.md. Will add run time logs. May refactor code later.

### CODE REVIEW

**Comment by lahoffm** [comment]
Please pull down lahoffm/master, merge into your master and resubmit pull request. So that you have lahoffm/master as it stands now, plus your addition of dekalb. Shouldn't be a problem. Accepting request as stands now would delete a couple folders on lahoffm/master (athensclarke, bibb, henry, glynn) and I'd have to do some extra merging work.

**Comment by lahoffm** [comment]
Looks like wonderful work but I won't have time to review in detail till next week (visiting family all weekend). I'll merge it once you did what I said in last comment, but I might be doing family things all day tomorrow.

**Comment by lahoffm** [comment]
Actually, better would be to make your own code, a separate branch (which you can branch off of as you usually would), and your **master** branch is always an up-to-date copy of lahoffm/master. You can pull into your "master" from lahoffm/master periodically to keep it up-to-date with lahoffm/master without fear of affecting your development branch. Then checkout development and merge your "master" (the up-to-date copy of lahoffm/master) into your development branch. And finally, submit pull request FROM the development branch (which is latest lahoffm/master plus your code on top). I was taught to do it this way at an Anidata open source project.

**Comment by rimjieun** [comment]
Ahh I see...I removed the other county folders from my master branch after pulling from lahoffm/master a couple days ago (because I'm stupid haha sigh). I'm trying to pull again from lahoffm/master but now it's saying "Already up-to-date". I think the problem is that there are no new changes to grab from lahoffm/master since my last pull so it's not grabbing the county folders...Do you mind committing some sort of change (like add a period or something) in lahoffm/master so I can pull again?

**Comment by lahoffm** [comment]
Oh man it's more complicated than I thought. Make sure you use gitk to see where everything is before you do next steps, if you didn't know about that command already.

I suspect it's saying already up to date for this reason: https://stackoverflow.com/questions/634546/git-merge-reports-already-up-to-date-though-there-is-a-difference

If you try just "git fetch" of lahoffm/master, your situation should match what is described on Stackoverflow and then trying to "git merge" lahoffm/master into your "master" after that, should tell you "already up to date" (since that's the 2nd part of "git pull"). So remotes/lahoffm/master that you pulled down should be in a direct line of commits to your master. But "git diff" should reveal lots of changes even though it says up to date. Please tell me if I'm wrong.

I haven't encountered this situation before, but my best guess right now would be, to do "git fetch" of lahoffm/master. Then, whichever commit it points to in  `gitk --all` is the state of the files as they are now in lahoffm/master. Then, checkout your "master", and use the "git checkout" command to get back the folders that you had deleted earlier. Something like the below but for folders instead of single files (not sure if you can just specify the folder).

```git checkout c6fab02 src/helloworld.py``` - checkout a file from the commit whose SHA started with ```c6fab02```  
```git commit –a –m “restore helloworld.py from commit c6fab02”```  - commit the file you checked out, which was from an earlier commit

So yeah you'll basically restore what you deleted (from current state of lahoffm/master) and make THAT a commit, then the pull request shows up on my end as "no changes except in Dekalb folder"

**Comment by lahoffm** [comment]
If I did do a tiny commit and you pulled it, I think the files you deleted would still be deleted when you merged it into your master.  Can you do me a favor and try this out yourself with a branch that you make? Make a branch off of the lahoffm/master commit that you fetched as https://stackoverflow.com/questions/2816715/branch-from-a-previous-commit-using-git, commit a tiny change, switch to your master and try to merge that branch into your master. I'm just curious if I'm right about that.

**Comment by rimjieun** [comment]
Oh wow thanks for looking into this! I'll try the second suggestion you posted. Give me a few minutes.

**Comment by rimjieun** [comment]
I just ended up re-forking and replacing the Dekalb folder. Submitted a new pull request. Hopefully there won't be any conflicts this time (except maybe in the Dekalb folder).

**Comment by rimjieun** [comment]
And you were right, when I merged the new branch into the master the files got deleted.

**Comment by lahoffm** [comment]
Merged the other one

**Pull request closed without merging**
